name: pubnub-angular2
version: 1.0.3
schema: 1
scm: github.com/pubnub/pubnub-angular2
files:
  - dist/pubnub-angular2.js
  - dist/pubnub-angular2.min.js
changelog:
  - version: v1.0.3
    changes:
      - type: bug
        text: fix issue 20 autoload history
      - type: improvement
        text: update for Angular4 and TS 2.3
  - version: v1.0.2
    changes:
      - type: bug
        text: fix issue over commmand 'ng build --prod' in Angular CLI
  - version: v1.0.1
    changes:
      - type: bug
        text: fix issue 15 reconnection event error
  - version: v1.0.0
    changes:
      - type: feature
        text: release final beta
  - version: v1.0.0.beta.9
    changes:
      - type: feature
        text: fix ionic2 bootstrap logic.
  - version: v1.0.0.beta.8
    changes:
      - type: feature
        text: additional typescript support
  - version: v1.0.0.beta.7
    changes:
      - type: feature
        text: first-class support for typescript.
  - version: v1.0.0.beta.6
    changes:
      - type: feature
        text: invoke pubnub features via HTML
  - version: v1.0.0.beta.5
    changes:
      - type: feature
        text: events are now broadcast to all instances
  - version: v1.0.0.beta.4
    changes:
      - type: feature
        text: error emitter
  - version: v1.0.0.beta.3
    changes:
      - type: feature
        text: first public beta of the wrapper.
  - version: v1.0.0.beta.2
    changes:
      - type: feature
        text: first public beta of the wrapper.
