name: pubnub-angular2
version: 1.3.2
schema: 1
scm: github.com/pubnub/pubnub-angular2
files:
  - dist/pubnub-angular2.js
  - dist/pubnub-angular2.min.js
changelog:
  - version: v1.3.2
    changes:
      - type: improvement
        text: update dependencies
    date: Dec 21, 2018
  - version: v1.3.1
    changes:
      - type: bug
        text: add functions to (fetchMessages and deleteMessages) to declaration files for TS
    date: Aug 6, 2018
  - version: v1.3.0
    changes:
      - type: feature
        text: add functions to (fetchMessages and deleteMessages) and keep the stack of messages with only the latest 100
    date: Nov 28, 2017
  - version: v1.2.0
    changes:
      - type: feature
        text: add support for environments CLI/no CLI simultaneously
    date: 2017-10-04
  - version: v1.1.0
    changes:
      - type: feature
        text: add release method
    date: 2017-06-20
  - version: v1.0.3
    changes:
      - type: bug
        text: fix issue 20 autoload history
      - type: improvement
        text: update for Angular4 and TS 2.3
    date: 2017-06-16
  - version: v1.0.2
    changes:
      - type: bug
        text: fix issue over commmand 'ng build --prod' in Angular CLI
    date: 2017-04-03
  - version: v1.0.1
    changes:
      - type: bug
        text: fix issue 15 reconnection event error
    date: 2017-02-28
  - version: v1.0.0
    changes:
      - type: feature
        text: release final beta
    date: 2017-02-23
  - version: v1.0.0.beta.9
    changes:
      - type: feature
        text: fix ionic2 bootstrap logic.
    date: 2017-02-13
  - version: v1.0.0.beta.8
    changes:
      - type: feature
        text: additional typescript support
    date: 2017-01-16
  - version: v1.0.0.beta.7
    changes:
      - type: feature
        text: first-class support for typescript.
    date: 2016-12-29
  - version: v1.0.0.beta.6
    changes:
      - type: feature
        text: invoke pubnub features via HTML
    date: 2016-11-22
  - version: v1.0.0.beta.5
    changes:
      - type: feature
        text: events are now broadcast to all instances
    date: 2016-11-18
  - version: v1.0.0.beta.4
    changes:
      - type: feature
        text: error emitter
    date: 2016-11-14
  - version: v1.0.0.beta.3
    changes:
      - type: feature
        text: first public beta of the wrapper
    date: 2016-11-03
  - version: v1.0.0.beta.2
    changes:
      - type: feature
        text: first public beta of the wrapper
    date: 2016-11-02
