name: pubnub-angular2
version: 1.0.0-beta.8
schema: 1
scm: github.com/pubnub/pubnub-angular2
changelog:
  - version: v1.0.0.beta.8
    changes:
      - type: feature
        text: additional typescript support
  - version: v1.0.0.beta.7
    changes:
      - type: feature
        text: first-class support for typescript.
  - version: v1.0.0.beta.6
    changes:
      - type: feature
        text: invoke pubnub features via HTML
  - version: v1.0.0.beta.5
    changes:
      - type: feature
        text: events are now broadcast to all instances
  - version: v1.0.0.beta.4
    changes:
      - type: feature
        text: error emitter
  - version: v1.0.0.beta.3
    changes:
      - type: feature
        text: first public beta of the wrapper.
  - version: v1.0.0.beta.2
    changes:
      - type: feature
        text: first public beta of the wrapper.
