export declare class Wrapper {
    constructor();
    init(initConfig: Object);
    getLabel(): string;
    getOriginalInstance(): any;
    subscribe(args: Object): void;
    unsubscribe(args: Object): void;
    unsubscribeAll(): void;
    getMessage(channel: string | string[]): Object[];
    getMessage(channel: string | string[], callback: (message: Object) => void): Object[];
    getPresence(channel: string | string[], callback: (presence: Object) => void): void;
    getStatus(channel: string | string[], callback: (status: Object) => void): void;
    getError(channel: string | string[], callback: (error: Object) => void): void;
    clean(channel: string | string[]): void;
    publish(message: Object): any;
    fire(args: Object): Object;
    addListener(listener: Object): void;
    removeListener(listener: Object): void;
    removeAllListeners(): void;
    hereNow(args: Object): any;
    whereNow(args: Object): any;
    getState(args: Object): any;
    setState(args: Object): any;
    grant(args: Object): any;
    channelGroups: any;
    history(args: Object): any;
    push: Object;
    time(): any;
    reconnect(): void;
    stop(): void;
    encrypt(data: string): string;
    encrypt(data: string, customCipherKey: string): string;
    decrypt(data: Object): string;
    decrypt(data: Object, customCipherKey: string): string;
    getAuthKey(): string;
    setAuthKey(key: string): void;
    getUUID(): string;
    setUUID(uuid: string): void;
    getFilterExpression(): string;
    setFilterExpression(setFilterExpression: string): void;
}
